### ISSUE TITLE
Remove brand from serverbound information

### ISSUE THREAD

**Issue by Madis0** [haykam821/Debrand#1]
Aka bundle this: https://github.com/liachmodded/brandpacket

**Comment by Mhowser** [comment]
Brandpacket does not change internal branding, it only changes what is sent to a multiplayer server.

**Comment by haykam821** [comment]
While I see the use for this, Debrand focuses mostly on stripping the brand from the Minecraft client’s screens rather than its networking. I think it would be better as its own mod.
