### ISSUE TITLE
Mod config not registered (Client startup crash)

### ISSUE THREAD

**Issue by Cynosphere** [haykam821/Debrand#2]
```
java.lang.RuntimeException: Config 'class io.github.haykam821.debrand.config.ModConfig' has not been registered
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.getConfigHolder(AutoConfig.java:57)
```

**Comment by SwanX1** [comment]
Have the same issue

**Comment by haykam821** [comment]
Are you on a snapshot version of 1.16?

**Comment by SwanX1** [comment]
> Are you on a snapshot version of 1.16?

No, latest 1.15.2

**Comment by haykam821** [comment]
Does it happen every time?

**Comment by SwanX1** [comment]
> 
> 
> Does it happen every time?

Yes (sorry for late response)

**Comment by haykam821** [comment]
Is this still an issue on [version 1.0.2](https://github.com/haykam821/Debrand/releases/tag/1.0.2)?

**Comment by SwanX1** [comment]
> Is this still an issue on [version 1.0.2](https://github.com/haykam821/Debrand/releases/tag/1.0.2)?

No, mod works as intended! Thank you!
