### ISSUE TITLE
[Suggestion] Add this amazing mod to Modrinth

### ISSUE THREAD

**Issue by Big-Iron-Cheems** [haykam821/Debrand#7]
First of all, thank you for making this. It's a really simple concept, but it gets the job done perfectly. 🎉 

Now, for the real point of this request.
You probably know that [Modrinth](https://modrinth.com/) was created as an alternative to Curseforge.
This website is entirely dedicated to Minecraft,
while Curseforge is a messy collection of mods for various games
(_with some of the worst search filters regarding MC mods, if I may say_).

I'd love to see your mod being added to it, since it is way more user and modder friendly.
I hope you consider this request, and thanks anyways if you decide not to do this.

**Comment by haykam821** [comment]
This project is now available on Modrinth [here](https://modrinth.com/mod/debrand).
